"""Generate untrusted witnesses; Lean independently checks every finite case."""
from pathlib import Path


def rows(n, g):
    a = [[False] * n for _ in range(n)]
    for j in range(n):
        for i in range(j):
            a[i][j] = a[j][i] = bool(g >> (j * (j - 1) // 2 + i) & 1)
    return a


def two_connected(a):
    n = len(a)
    for removed in range(n):
        seen = {next(i for i in range(n) if i != removed)}
        todo = list(seen)
        while todo:
            i = todo.pop()
            for j in range(n):
                if j != removed and a[i][j] and j not in seen:
                    seen.add(j)
                    todo.append(j)
        if len(seen) != n - 1:
            return False
    return True


def gap(a):
    n = len(a)
    d = [[0 if i == j else 1 if a[i][j] else n for j in range(n)] for i in range(n)]
    for k in range(n):
        for i in range(n):
            for j in range(n):
                d[i][j] = min(d[i][j], d[i][k] + d[k][j])
    sz = w = 0
    for j in range(n):
        for i in range(j):
            w += d[i][j]
            if a[i][j]:
                sz += sum(d[x][i] < d[x][j] for x in range(n)) * sum(d[x][j] < d[x][i] for x in range(n))
    return sz - w


def iso(a, b):
    n = len(a)
    da, db = list(map(sum, a)), list(map(sum, b))
    if sorted(da) != sorted(db):
        return None
    order = sorted(range(n), key=lambda i: (da.count(da[i]), -da[i]))
    p, used = [-1] * n, set()

    def visit(k):
        if k == n:
            return p.copy()
        i = order[k]
        for j in range(n):
            if j in used or da[i] != db[j]:
                continue
            if any(a[i][t] != b[j][p[t]] for t in order[:k]):
                continue
            p[i] = j
            used.add(j)
            result = visit(k + 1)
            if result is not None:
                return result
            used.remove(j)
        return None

    return visit(0)


def generate():
    result = {}
    previous = []
    for n in range(5, 11):
        codes = range(1 << 10) if n == 5 else sorted({g | (s << ((n-1)*(n-2)//2)) for g in previous for s in range(1 << (n-1))})
        reps, matrices, table = [], [], []
        for g in codes:
            a = rows(n, g)
            if not two_connected(a) or gap(a) >= 2*n:
                continue
            for r, b in zip(reps, matrices):
                p = iso(a, b)
                if p is not None:
                    break
            else:
                r, p = g, list(range(n))
                reps.append(g)
                matrices.append(a)
            packed = sum(v * n**i for i, v in enumerate(p))
            table.append([g, r, packed])
        result[n] = dict(reps=reps, table=table)
        exceptional = [sum(1 << (j*(j-1)//2+i) for j in range(n) for i in range(j)
                           if i != 0 or j <= t) for t in [n-1, 2, n-2]]
        for g in exceptional:
            if any(row[0] == g for row in table):
                continue
            for r, b in zip(reps, matrices):
                p = iso(rows(n, g), b)
                if p is not None:
                    table.append([g, r, sum(v*n**i for i,v in enumerate(p))])
                    break
            else:
                raise AssertionError('Missing exceptional representative')
        if n == 10:
            for r in reps:
                for t, g in zip([n-1, 2, n-2], exceptional):
                    p = iso(rows(n, r), rows(n, g))
                    if p is not None:
                        print('final', r, t, sum(v*n**i for i,v in enumerate(p)), flush=True)
                        break
        previous = reps
        print(n, 'representatives:', len(reps), 'witnesses:', len(table), 'gaps:', [gap(a) for a in matrices], flush=True)
    output = (Path(__file__).resolve().parents[1] /
              'Proof/ExternalResults/BKLPSOrderTenCheck/OrderTenCertificateData.lean')
    lines = ['/-! Untrusted labeling witnesses generated by `scripts/order_ten_certificate.py`.',
             'The finite checks in OrderTenClassification validate these data. -/',
             'namespace BKLPS.External.OrderTenCertificate', '']
    for n, data in result.items():
        data['table'].sort(key=lambda row: row[0])
        lines.append(f'def reps{n} : List Nat := {data["reps"]}')
        lines.append(f'def table{n} : List (Nat × Nat × Nat) := [')
        lines.append(',\n'.join(f'  ({g}, {r}, {p})' for g, r, p in data['table']))
        lines.append(']\n')
    lines.append('end BKLPS.External.OrderTenCertificate\n')
    output.write_text('\n'.join(lines), encoding='utf-8')


if __name__ == '__main__':
    generate()
